default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: <%= ENV.fetch("MYSQL_HOST") { "localhost" } %>

development:
  <<: *default
  database: task-three-development

test:
  <<: *default
  database: task-three-test

production:
  <<: *default
  password: <%= ENV.fetch("MYSQL_PASS") { "" } %>
  database: task-three-production
